variables:
  CI_IMAGE: registry.gitlab.com/qbau/software-and-apps/ci-dockerfiles/ubuntu_amd64-22.04:all_dep_clang-5
  # CORE_REF specifies the reference to copy artifacts from e.g. "refs/merge-requests/209/head"
  # default is "main"
  CORE_REF: main

stages:
  - build
  - test
  - deploy

.install-core:
  before_script:
    - echo $PWD
    - ls *
    - whoami
    - export ORIG=$PWD
    - export ARTEFACTS_DIR=$PWD/../core
    - rm -rf ${ARTEFACTS_DIR} ${QB_DIR}/core
    - mv core_artefacts ${ARTEFACTS_DIR}
    - cmake --install ${ARTEFACTS_DIR}/build
    - cd $ORIG

build-test-apps:
  stage: build
  needs:
    - project: qbau/software-and-apps/core
      job: ci-build
      ref: $CORE_REF
      artifacts: true
  extends: .install-core
  image: $CI_IMAGE
  tags: ["cutensornet2.0"]
  script:
    - echo "*"
    - echo "* Introduction to Nextflow test"
    - echo "*"
    - START_DIR=`pwd`
    - cd nextflow/introduction
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${QB_DIR}/core
    - make install
    - cd ${QB_DIR}/core/examples/cpp/vqe_opt_hpc_app
    - mkdir build
    - cd build
    - cmake ..
    - make
    - echo "*"
    - echo "* QM/MM H20-H2 simple test"
    - echo "*"
    - cd ${QB_DIR}/core/examples/cpp/vqeeCalculator
    - mkdir build
    - cd build
    - cmake ..
    - make
    - echo "*"
    - echo "* Setting up artifacts for dependent tasks to consume"
    - echo "*"
    - cd ${START_DIR}
    - mkdir build-test-apps-artifacts
    - cp -pr ${QB_DIR}/core/examples/cpp/vqeeCalculator build-test-apps-artifacts/.
    - cp -pr ${QB_DIR}/core/examples/cpp/vqe_opt_hpc_app build-test-apps-artifacts/.
  artifacts:
    paths:
      - build-test-apps-artifacts/

ci-shell-nextflow-tests:
  stage: test
  needs:
    - project: qbau/software-and-apps/core
      job: ci-build
      ref: $CORE_REF
      artifacts: true
    - job: build-test-apps
      artifacts: true
  extends: .install-core
  image: $CI_IMAGE
  tags: ["cutensornet2.0"]
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - export JAVA_CMD=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - mkdir -p ${HOME}/.local/bin
    - pushd ${HOME}/.local/bin
    - curl -s https://get.nextflow.io | NXF_VER=24.10.6 bash
    - popd
    - cp -pr build-test-apps-artifacts/vqe_opt_hpc_app ${QB_DIR}/core/examples/cpp/.
    - export OPT_APP_DIR=${QB_DIR}/core/examples/cpp/vqe_opt_hpc_app/build
    - cd $ORIG/nextflow/introduction
    - NQPUS=2
    - NATOMS=$(cat ../../tests/nextflow/introduction/2-hydrogen.geo | wc -l)
    - echo "Run with Nextflow"
    - nextflow run main.nf -profile standard --bin_dir "${OPT_APP_DIR}"
    - echo "Run without Nextflow"
    - cat ../../tests/nextflow/introduction/2-hydrogen.geo | mpiexec --allow-run-as-root -n $NQPUS $OPT_APP_DIR/vqe_opt_hpc_app --n-hydrogens $NATOMS --n-virtual-qpus $NQPUS
  artifacts:
    when: always
    paths:
      - nextflow/introduction/all_results.log

ci-py-nextflow-tests:
  stage: test
  needs:
    - project: qbau/software-and-apps/core
      job: ci-build
      ref: $CORE_REF
      artifacts: true
    - job: build-test-apps
      artifacts: true
  extends: .install-core
  image: $CI_IMAGE
  tags: ["cutensornet2.0"]
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - export JAVA_CMD=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - export QRISTAL_INSTALL_DIR=${QB_DIR}/core
    - export NF_RESOURCES=$ORIG/nextflow/introduction
    - mkdir -p ${HOME}/.local/bin
    - pushd ${HOME}/.local/bin
    - curl -s https://get.nextflow.io | NXF_VER=24.10.6 bash
    - popd
    - echo "Simple Nextflow Python test"
    - python3 -m pip install nextflowpy==0.5.0
    # Roll back to earlier version of scipy for compatibility with ASE 3.22.1
    - python3 -m pip install scipy==1.13.1
    - cp -pr build-test-apps-artifacts/vqe_opt_hpc_app ${QB_DIR}/core/examples/cpp/.
    - cd $ORIG/tests/nextflow/introduction
    - python3 -m pytest run.py
    - echo "QM/MM test"
    - cd $ORIG
    - cp -pr build-test-apps-artifacts/vqeeCalculator ${QB_DIR}/core/examples/cpp/.
    - cd nextflow/q_chemistry
    - python3 qm_mm.py -f 0.3 -p -q 2 -c ${QB_DIR}/core/examples/cpp/vqeeCalculator/build/vqeeCalculator
    - ase gui -n -1 opt.traj -o ../../tests/nextflow/q_chemistry/last.xyz
    - cd ../../tests/nextflow/q_chemistry
    - python3 -m pytest --junitxml="report-qmmm.xml"
  artifacts:
    when: always
    reports:
      junit: tests/nextflow/q_chemistry/report-qmmm.xml

ci-py-qiskit-tests:
  stage: test
  needs:
    - project: qbau/software-and-apps/core
      job: ci-build
      ref: $CORE_REF
      artifacts: true
  extends: .install-core
  image: $CI_IMAGE
  tags: ["cutensornet2.0"]
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - export QRISTAL_INSTALL_DIR=${QB_DIR}/core
    - python3 -m venv $ORIG/qiskit_1.2.0
    - source $ORIG/qiskit_1.2.0/bin/activate
    - export PYTHONPATH=$QRISTAL_INSTALL_DIR/lib:$ORIG:$PYTHONPATH
    - python3 -m pip install pytest==8.3.5
    - python3 -m pip install networkx==3.4.2
    - python3 -m pip install numpy==2.2.5
    - python3 -m pip install pyscf==2.9.0
    - python3 -m pip install qiskit==1.2.0
    - python3 -m pip install qiskit-algorithms==0.3.1
    - python3 -m pip install qiskit-nature==0.7.2
    - python3 -m pip install qiskit-optimization==0.6.1
    - cd $ORIG/tests/qiskit_integration
    - python3 -m pytest --junitxml="report-qiskit.xml"
    - cd $ORIG/qiskit_integration
    - python3 circuit_example.py
    - deactivate
  artifacts:
    when: always
    reports:
      junit: tests/qiskit_integration/report-qiskit.xml
